### PR TITLE
Added support for Select field type.

### PR DESCRIPTION
**Pull request by ymauray**
I'm working on a couple of plugins, and they will require a new type of field in the UI : Select (same as text-align, but configurable from the plugin).
Thanks.

### CODE REVIEW

**Comment by ymauray** [comment]
Corresponding PR for the API : https://github.com/unix-streamdeck/api/pull/7

**Comment by ymauray** [comment]
There you go, updated `go.mod` to point to API 1.0.1

**Comment by The-Jonsey** [comment]
you'll need to run a `go mod tidy` first to update the go.sum file, so references get updated, otherwise it could cause errors on go install

**Review by andydotxyz — APPROVED** [review]

**Comment by ymauray** [comment]
Oh sorry! I'm a `go` beginner, I just started last weekend, specifically to work on some plugins for this project.

**Comment by The-Jonsey** [comment]
yeah no problem, all of this is my first go project too :laughing:

**Pull request merged**
