### PR TITLE
Feature : copy/paste button

### PR DESCRIPTION
**Pull request by ymauray**
This pull request adds 2 actions to the toolbar :
Copy button - copies the current button in a buffer
Paste button - if a button was copied before, pastes that button, overriding the current key configuration.

Also, it adds 3 keyboard shortcuts: CTRL-C/CTRL-V to copy and paste, and CTLS-S to save the config (while I was at it).

### CODE REVIEW

**Comment by The-Jonsey** [comment]
Hey, nice work, especially the keybinds, but have you tested that they don't override copying and pasting in the text boxes on the editor?

**Comment by ymauray** [comment]
Yep, it's all good. I suspect there are copy/paste shortcuts tied to the text fields, and they take precedence over the ones installed on the editor.

**Comment by The-Jonsey** [comment]
Cool, I'll give this a proper review tomorrow, I had kinda already wrote this with a small UI redesign, but I can just do the redesign

**Comment by andydotxyz** [comment]
> Yep, it's all good. I suspect there are copy/paste shortcuts tied to the text fields, and they take precedence over the ones installed on the editor.

Quite right, a focused widget gets shortcuts ahead of the window canvas.

**Comment by ymauray** [comment]
I suddenly have a doubt, about the way Go copies the object. Is that be ref or by value? There is a possibility that the original and the copied buttons are in fact the same. I'll check as soon as I get back home.

**Comment by ymauray** [comment]
All good!

**Comment by The-Jonsey** [comment]
also could you get the vscode config file gitignored and removed from this MR?

**Comment by ymauray** [comment]
There you go. Merry christmas!

**Comment by The-Jonsey** [comment]
Thanks. Merry Christmas to you too

**Pull request merged**
